DROP TABLE IF EXISTS bids CASCADE;
CREATE TABLE bids (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  item_id INTEGER REFERENCES items(id) ON DELETE CASCADE,
  bid_value INTEGER NOT NULL
);
